name: Setup fastlane
author: Furious Avocado
description: Move fastlane files in correct position
runs:
  using: "composite"
  steps:
    - name: Move fastlane files
      shell: bash
      run: |
        mv ${{ github.workspace }}/fabrika/fastlane ${{ github.workspace }}/fastlane
        mv ${{ github.workspace }}/fastlane/Gemfile ${{ github.workspace }}/Gemfile
        mv ${{ github.workspace }}/fastlane/Gemfile.lock ${{ github.workspace }}/Gemfile.lock

