name: Prepare the code for Odin as a dependency
author: Furious Avocado
description: This action goes through all .cs files and if they require Odin, or code that relies on Odin it wraps them with a compiler directive to only compile the code when Odin is present in the project.
inputs:
  branch:
    description: "The branch to prepare for Odin"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
        lfs: true

    - name: Set Git Config
      run: |
        git config --global user.name 'Furious Avocado CI'
        git config --global user.email 'ci@furiousavocado.com'
      shell: bash

    - name: Pass .cs files and wrap with \#ifdef
      run: |
        for scriptFile in `find . -iname "*.cs" -type f`
        do
            shouldWrapFile=false
            usings=( 'Sirenix' 'FuriousAvocado' )

            for using in "${usings[@]}"; do
                if grep -q -wF -e "$using" "$scriptFile"; then
                    shouldWrapFile=true
                fi
            done

            if $shouldWrapFile ; then
                echo '#if ODIN_INSPECTOR && ODIN_INSPECTOR_3 && ODIN_VALIDATOR' > tmp.txt
                cat $scriptFile >> tmp.txt
                echo $'#endif' >> tmp.txt
                mv tmp.txt $scriptFile
            fi
        done
      shell: bash

    - name: Commit changed files
      run: |
        git commit -am "Wrapped with Odin's Furious Thunder."
        git push
      shell: bash
