name: Prepare the code for Odin as a dependency
author: Furious Avocado
description: This action goes through all .cs files and if they require Odin, or code that relies on Odin it wraps them with a compiler directive to only compile the code when Odin is present in the project.
inputs:
  branch:
    description: "The branch to prepare for Odin"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
        lfs: true

    - name: Set Git Config
      run: |
        git config --global user.name 'Furious CI'
        git config --global user.email 'ci@furiousavocado.com'
      shell: bash

    - name: Download Odin Wrapper file
      run: curl https://raw.githubusercontent.com/Furious-Avocado/fabrika/master/wrap_cs_files.sh -o ${{ github.workspace }}/wrap_cs_files.sh
      shell: bash

    - name: Pass .cs files and wrap with \#ifdef
      run: |
        chmod +x "${{ github.workspace }}/wrap_cs_files.sh"
        "${{ github.workspace }}/wrap_cs_files.sh"
      shell: bash

    - name: Commit changed files
      run: |
        git commit -am "Wrapped with Odin's Furious Thunder."
        git push
      shell: bash
