name: Build FA Library for UPM
on: 
  workflow_call:
    inputs:
      libFolderName:
        required: true
        type: string
      version:
        required: false
        type: string 
jobs:
  build:
    name: Build and Publish Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set Git Config
        run: |
          git config --global user.name 'Furious Avocado CI'
          git config --global user.email 'ci@furiousavocado.com'

      - name: Auto Increment Version (if applicable)
        if: ${{ inputs.version == null }}
        run: |
          npm version patch --prefix Assets/${{ inputs.libFolderName }}

      - name: Manually Set Version (if applicable)
        if: ${{ inputs.version != null }}
        run: |
          echo "$(cat Assets/*/package.json | jq '.version = "${{ inputs.version }}"')" > Assets/*/package.json

      - name: Write version and name to ENV for other steps
        run: |
          newVersion=$(cat Assets/*/package.json | jq -r '.version')
          packageName=$(cat Assets/*/package.json | jq -r '.name')
          echo "newVersion=$newVersion" >> $GITHUB_ENV
          echo "packageName=$packageName" >> $GITHUB_ENV
        
      - name: Push version increment to Github
        run: |
          git commit -am "Incrementing Version to $newVersion."
          git push

      - name: Update UPM Branch
        run: |
          git push origin --delete upm &> /dev/null || echo No UMP branch to delete.
          git subtree push --prefix Assets/${{ inputs.libFolderName }} origin upm
          git reset --hard
          git checkout upm

      - name: Update Samples location
        run: |
          if [[ -d "Samples" ]]; then
            git mv Samples Samples~
            rm -f Samples.meta
            git add .
            git commit -m "Updated Samples~ folder name per UPM."
            git push origin upm
          fi
